const USERS_COLLECTION = "users";
const QUESTIONS_COLLECTION = "questions";
const QUESTION_TYPE_CHOICE = "choice";
const CONTENT_SOURCE_TEXT = "text";
const CONTENT_SOURCE_IMAGE = "image";
const ENTRY_MODE_SINGLE = "single";
const ENTRY_MODE_GROUPED = "grouped";
const OPTION_MODE_PER_OPTION = "per_option";
const OPTION_MODE_GROUPED_ASSET = "grouped_asset";

module.exports = {
  USERS_COLLECTION,
  QUESTIONS_COLLECTION,
  QUESTION_TYPE_CHOICE,
  CONTENT_SOURCE_TEXT,
  CONTENT_SOURCE_IMAGE,
  ENTRY_MODE_SINGLE,
  ENTRY_MODE_GROUPED,
  OPTION_MODE_PER_OPTION,
  OPTION_MODE_GROUPED_ASSET,
};
